### ISSUE TITLE
Unclosed File Connection when reading multiple files

### ISSUE THREAD

**Issue by MaximilianJHuber** [JuliaComputing/TextParse.jl#52] opened 2018-03-13 22:48 UTC
I read two .csv files with 330MB each using `TextParse 0.4.1`:
```
using TextParse
types = [...] #correct parsers
file_names = [...] #two absolute paths to the files
TextParse.csvread(file_names, ',', colparsers = types)
```
It parses correctly.

Immediately afterward I remove the first file by hand, which works, but the second one doesn't. Windows tells me it is open in another program. This is odd because [csvread](https://github.com/JuliaComputing/TextParse.jl/blob/804bbb0eed1b3a11f506549ffc957ff43313a738/src/csv.jl#L104) calls [_csvread_f](https://github.com/JuliaComputing/TextParse.jl/blob/804bbb0eed1b3a11f506549ffc957ff43313a738/src/csv.jl#L85) which calls [open](https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/iostream.jl#L149) which closes the connection in a `finally` statement.

**Comment by quinnj** [comment] 2018-03-13 22:53
It's probably because there hasn't been a `gc()` since `close` happened on the file IOStream. If you call `gc(); gc()` manually, you should be able to remove.

**Comment by MaximilianJHuber** [comment] 2018-03-13 23:04
Yes, that worked! Is that a common gotcha?

**Comment by quinnj** [comment] 2018-03-13 23:08
Yes, on windows, we need a full `gc` to release the underlying mmapped files before they're deleteable. We should really figure out a better solution since this comes up _all_ the time; maybe we should just call `gc` from `close` in Base. @vtjnash, any thoughts on how we can solve this? or are we doomed to keep answering this forever....

**Comment by vtjnash** [comment] 2018-03-14 03:19
Is this because the stream is being pinned by `mmap`? You should probably not use mmap unless the user explicitly asks for it. In addition to being less reliable all around, I suspect it may also often be slower (due to the increased memory pressure, less predictable context switches, and mandatory thread-stall while fetching the data from disk).

**Comment by MaximilianJHuber** [comment] 2018-03-14 16:50
@vtjnash `mmap` is less reliable than what?

**Comment by vtjnash** [comment] 2018-03-14 17:27
Explicit file IO (aka read/write)

**Comment by MaximilianJHuber** [comment] 2018-03-14 18:07
Thanks! Well, I can confirm that when I load a CSV the worker runs at 100% CPU, but the disk is reading at 30MB/s, while the maximal speed is probably around 150MB/s.

**Comment by davidanthoff** [comment] 2019-01-06 23:33
Closing as a duplicate of https://github.com/JuliaComputing/TextParse.jl/issues/20.

**Closed by davidanthoff** 2019-01-06 23:33 UTC
Labels: bug
